services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: agri-insight-app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${HOST_PORT}:${HOST_PORT}"  # Expose app port to host
    depends_on:
      - db
      - libretranslate
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${HOST_PORT}", "--reload"]
    environment:
      # Optional: add internal URLs for LibreTranslate and DB
      - DATABASE_URL=${DATABASE_URL}
      - LIBRETRANSLATE_URL=${TRANSLATE_API_ENDPOINT}

  db:
    image: supabase/postgres:17.6.1.029
    container_name: agri-insight-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,hi,bn
      - LT_FRONTEND_LANGUAGE=en
      - LT_API_KEY=${TRANSLATE_API_KEY}
    command: ["--host", "0.0.0.0", "--port", "5000"]

volumes:
  pgdata:
